#!/usr/bin/env bash

DEV_ENV="$HOME/personal/quark"
dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi


if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}


update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

ensure_parent_dir() {
    local parent
    parent="$(dirname "$1")"

    if [[ ! -d "$parent" ]]; then
        log "creating directory: $parent"

        if [[ $dry_run == "0" ]]; then
            mkdir -p "$parent"
        fi
    fi
}

copy() {
    if [[ ! -e "$1" ]]; then
        echo "ERROR: source does not exist: $1"
        return 1
    fi

    ensure_parent_dir "$2"

    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm -f "$2"
    fi

    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp "$1" "$2"
    fi
}
update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
update_files $DEV_ENV/env/.local $HOME/.local

copy $DEV_ENV/env/.local/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy $DEV_ENV/env/home/.zsh_profile $HOME/.zsh_profile
copy $DEV_ENV/env/home/.zshrc $HOME/.zshrc

copy $DEV_ENV/env/home/.tmux-sessionizer $HOME/.tmux-sessionizer
copy $DEV_ENV/env/.local/dev-env $HOME/.local/scripts/dev-env
copy $DEV_ENV/env/.local/dev-commit $HOME/.local/scripts/dev-commit
copy $DEV_ENV/env/.local/server $HOME/.local/scripts/server
copy $DEV_ENV/env/.local/screenshot $HOME/.local/scripts/screenshot

hyprctl reload
