wallpaper {
    monitor = eDP-1
    path =  ~/.config/wallpapers/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path =  ~/.config/wallpapers/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg
    fit_mode = cover
}
splash = false
